version: "3.7"
services:
    # image project
    cashgame:
        build: 
            args: 
                user: carlos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - projectx
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 80:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - projectx

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks: 
            - projectx

    # queue
    queue:
        build: 
            args: 
                user: carlos
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - projectx

    # redis
    redis:
        image: redis:latest
        networks: 
            - projectx

    adminer:
            image: phpmyadmin/phpmyadmin
            container_name: cashgame_phpmyadmin
            restart: unless-stopped
            tty: true
            ports:
              - "8080:80"
            environment:
              PMA_HOST: mysql
              UPLOAD_LIMIT: 300M
            depends_on:
              - mysql
            networks:
              - projectx  

networks: 
    projectx:
        driver: bridge